[project]
name = "uv-py-hardlink"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
  "markupsafe>=2.1.5",
  "nox"
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
